// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdWoFYdBXMKuwdptfHlqKCnzyrISUGyD0',
    appId: '1:863385941504:android:ec5058368a5913728c4ae5',
    messagingSenderId: '863385941504',
    projectId: 'ica-companion',
    databaseURL: 'https://ica-companion.firebaseio.com',
    storageBucket: 'ica-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIaGZwCtcctD0ErANHPrVcjH9x-m3ui9Y',
    appId: '1:863385941504:ios:1fd3afe6873022438c4ae5',
    messagingSenderId: '863385941504',
    projectId: 'ica-companion',
    databaseURL: 'https://ica-companion.firebaseio.com',
    storageBucket: 'ica-companion.firebasestorage.app',
    androidClientId: '863385941504-t88g7nsgb1fbrfqghjetcug1efucd6f1.apps.googleusercontent.com',
    iosClientId: '863385941504-81h30l1jdlnsikovgp07fdpttq36vn3q.apps.googleusercontent.com',
    iosBundleId: 'com.danielowusuacquah.ICA',
  );

}